receivers:
  redis:
    endpoint: localhost:6379
    collection_interval: 10s

exporters:
  otlp:
    endpoint: $OTEL_EXPORTER_OTLP_ENDPOINT

processors:
  resourcedetection:
    detectors: [env, system]
  cumulativetodelta:
  batch:
    timeout: 10s

service:
  pipelines:
    metrics:
      receivers: [redis]
      processors: [cumulativetodelta, batch, resourcedetection]
      exporters: [otlp]