name: "Push"
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.22.6'
          go-version-file: 'go.mod'
          cache: true

      - name: Build binaries
        run: go install ./cmd/...

  staticcheck:
    name: "Staticcheck"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.22.6'
          go-version-file: 'go.mod'
          cache: true

      - uses: dominikh/staticcheck-action@v1.3.1
        with:
          install-go: false

  errcheck:
    name: "Errcheck"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.22.6'
          go-version-file: 'go.mod'
          cache: true

      - run: go install github.com/kisielk/errcheck@latest
      - run: errcheck -ignore 'AddCheck' ./...