name: Release

on:
  create:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Fetch latest tag"
        id: get-latest-tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Build and push Dragonfly-flex
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          build-args: |
            DRAGONFLY_VERSION=1.23.0
            REDIS_VERSION=7.4.0
            VERSION=${{ steps.get-latest-tag.outputs.tag }}
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/streamersonglist/dragonfly-flex:latest
            ghcr.io/streamersonglist/dragonfly-flex:${{ steps.get-latest-tag.outputs.tag }}

      - name: Dragonfly-flex Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
